### ISSUE TITLE
Usuario incorrecto en unas estadísitcas del README

### ISSUE THREAD

**Issue by 15Galan** [Lucas-pin/Lucas-pin#1]
Cuidado, te dejaste mi usuario en [esta línea](https://github.com/Lucas-pin/Lucas-pin/blame/a84f3df0c997713aaea2788ca1c10b68c78192c8/README.md#L64) del README, así que en realidad estás mostrando **mis estadísticas**.

**Comment by Lucas-pin** [comment]
Solved! Gracias!
